### ISSUE TITLE
Read a wishlist

### ISSUE THREAD

**Issue by brentdur** [nyu-devops-golf-team/wishlist#2]
**As a** customer
**I need** to be able to retrieve a single wishlist by its id
**So that** I can get the product ids and name of the wishlist

**Assumptions:** 
* the list returned will not be one that's persisted

**Acceptance Criteria:**
```
Given that I have a wishlist id
When I make a request with that wishlist id
Then i get a wishlist with a name, id, and list of products
```

**Comment by DB3619** [comment]
This issue looks to me like a duplicate of querying a wishlist by name : Issue 4. The wishlist ID is maintained by us for internal use. So the customer has no information about the wishlist ID

**Comment by aashishdugar** [comment]
It does seem like a duplicate. Looks like pretty much the "get" method all over again.

**Comment by DB3619** [comment]
We will duplicate it.
