### ISSUE TITLE
Add packages for testing in requirements.txt file

### ISSUE THREAD

**Issue by PeterYHChen** [nyu-devops-golf-team/wishlist#26]
**As a** developer
**I need** have necessary testing packages installed on the virtual machine
**So that** I can easily run tests on the virtual machine without extra efforts

**Assumptions:** 
* Put necessary packages in the requirement.txt file, such as nosetests, coverage.
* Found in the professor's lab test code, the following package could be included
```
# Testing
pylint
mock==2.0.0
httpie==0.9.9
nose==1.3.7
rednose==1.2.1
pinocchio==0.4.2
# Rspec DSL
noseOfYeti==1.6
expects==0.8.0
# Code coverage
coverage==4.2
codecov==2.0.5
```
**Acceptance Criteria:**
```
When I run nosetests command in the virtual machine under /vagrant folder
Then I would successfully get tests result and a coverage report
```

**Comment by DB3619** [comment]
The coverage files are added to the requirements folder
