### ISSUE TITLE
List wishlists

### ISSUE THREAD

**Issue by PeterYHChen** [nyu-devops-golf-team/wishlist#6]
**As a** customer with id
**I need** list all the wishlists that I have created before
**So that** I can view and select a wishlist to check the products I want

**Assumptions:** 
* Create a data structure map to map each customer's id to a list of wishlists he/she has created
* The map data structure would maintain as long as the application is running

**Acceptance Criteria:**
```
Given a customer id
When I call the list wishlists URL
Then I should see a list of wishlists that I created before
```

**Comment by DB3619** [comment]
When I try running the main file "main.py" I get the following error : 
from flask import Flask, jsonify, request, url_for, make_response
ImportError : no module named flask
Anyone who knows the solution for this ?
