### ISSUE TITLE
Update a wishlist

### ISSUE THREAD

**Issue by DB3619** [nyu-devops-golf-team/wishlist#7]
**As a** customer
**I need** to update a wishlist
**So that** I can add a new product to it.

**Assumptions:** 
* Customer id is given
* Wishlist id is given
* Product id is given

**Acceptance Criteria:**
```
Given the Customer id , wishlist id and product id
When the request for update is received
Then the product id is added to the wishlist
```

**Comment by DB3619** [comment]
The find method used in update takes a customer id and wishlist name as input. The current implementation takes the wishlist ID. Thus the method requires some changes.

**Comment by aashishdugar** [comment]
Understood. We'll make the changes tomorrow. Thanks for bringing it up!

**Comment by PeterYHChen** [comment]
I just scanned over the codes we have, and I fixed the problem of failing to update a wishlist with products. I have generated a pull request for this, please review it and approve if you don't have problem.

It is a working version for this issue now, but I think you might have more codes to be added to it.

**Comment by DB3619** [comment]
I have done all the required changes for the update function
