### ISSUE TITLE
Create Vagrant Environment

### ISSUE THREAD

**Issue by aashishdugar** [nyu-devops-golf-team/wishlist#8]
**As a: Developer** 
**I need: To create a virtual environment for the team to work on**  
**So that: The team can work in a singular environment with no dependency issues**  

**Assumptions:** 
* Create a Vagrant file and embed the required tools.
* Upload Vagrant file to the organization repo for team to access.

**Acceptance Criteria:**

**Given: The developer gets the Vagrant File.**
**When: They run vagrant up and vagrant ssh**
**Then: They can run the necessary files in the environment and start developing**

**Comment by aashishdugar** [comment]
Uploaded the Vagrantfile, waiting for team review.
Tools added so far - 
* Redis Container
* Python/Python flask
* Apache2

**Comment by DB3619** [comment]
The Vagrant file is not working. There are issues with it : 
1 Not able to connect to the browser with a simple application like app.py from the lab folders used in class.
Please run the app.py file using this vagrantfile to spot the issue and also look at some differences between this vagrant file and the one used in class.

**Comment by aashishdugar** [comment]
Ok for connecting to the browser,did you check the port number you're connecting to?

**Comment by aashishdugar** [comment]
![screenshot 16](https://user-images.githubusercontent.com/31813549/31356100-bc3a5374-ad0a-11e7-9029-dc778e15f944.png)

Just a preview with the same Vagrantfile, it works fine for me.

**Comment by PeterYHChen** [comment]
It works for me, but I have a question about the vagrant file location. Would it be easier for application deployment if we have the vagrantfile in the root /wishlist/ folder instead of having its own /wishlist/Vagrant/ folder?

**Comment by DB3619** [comment]
Have it in the root....

**Comment by aashishdugar** [comment]
Yea ill move it to the root.

**Comment by aashishdugar** [comment]
Also let's keep it in done for now because I'm still not sure if we'll need more tools appended to it. Once we're done with that, ill close the issue.
